import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Header from "@/components/layout/Header";
import Footer from "@/components/layout/Footer";



const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Velocity-app",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className={`${geistSans.variable} ${geistMono.variable} min-h-screen flex flex-col`}>
        <script
          dangerouslySetInnerHTML={{
            __html: `
              (() => {
                try {
                  const legacy = localStorage.getItem("settings-theme") || localStorage.getItem("ettings-theme");
                  const stored = localStorage.getItem("app-theme");
                  const rawPreference = stored || legacy || "system";
                  const preference = rawPreference === "light" || rawPreference === "dark" || rawPreference === "system"
                    ? rawPreference
                    : "system";
                  localStorage.setItem("app-theme", preference);
                  localStorage.removeItem("settings-theme");
                  localStorage.removeItem("ettings-theme");
                  const isDark = preference === "dark" || (preference === "system" && window.matchMedia("(prefers-color-scheme: dark)").matches);
                  document.documentElement.classList.toggle("dark", isDark);
                  document.documentElement.setAttribute("data-theme", isDark ? "dark" : "light");
                } catch (_) {}
              })();
            `,
          }}
        />

            
            <Header/>
              <main className="flex-1">
                {children}
              </main>
            <Footer/>


      </body>
    </html>
  );
}
